import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Auth from "@/components/auth/Auth";
import NavBarComponent from "@/components/header/NavBar";
import { isAuthenticated } from "@/utils/amplify-utils";
import FooterComponent from "@/components/Footer";
import HeaderComponent from "@/components/header/HeaderComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Auth>
          <main className="bg-zinc-200">
            
            <HeaderComponent />
            
          </main>

          {children}

          <FooterComponent/>

        </Auth>
      </body>
    </html>
  );
}
